In [2]:
# K-Fold help for evaluating model performance
# eg. Identifying digits with model (Logistic Regression, 

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from sklearn.datasets import load_digits
digits = load_digits()

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [7]:
# Below is example of checking model accuracy for digits individually 

In [8]:
# By Logistic Regression
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test) 

C:\Users\rosha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [9]:
# By SVC
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9851851851851852

In [10]:
# By Random Forest
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [11]:
# Now by K-Fold classification

In [12]:
from sklearn.model_selection import KFold
Kf = KFold(n_splits=3)
Kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_index, test_index in Kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [15]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\rosha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [16]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index],digits.target[train_index], digits.target[test_index]

    scores_logistic.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

C:\Users\rosha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\rosha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the 

In [17]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [18]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [20]:
scores_rf

[0.9365609348914858, 0.9532554257095158, 0.9248747913188647]

In [21]:
# doing all k-ford work in a few line 
from sklearn.model_selection import cross_val_score

In [24]:
# For LogisticRegression
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\rosha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\rosha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the 

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [26]:
# For SVM
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [27]:
# For RandomForestClassifier
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.92777778, 0.91111111, 0.9637883 , 0.96657382, 0.92200557])

In [28]:
# with cross_val_score we can find the actual result of the models 

In [32]:
# Putting more parameters for finding actual res for RandomForestClassifier
Rscores = cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target,cv=10)
Rscores

# n_estimator means no. of Trees (True,False tree)
# cv means no. of value required to return

array([0.85555556, 0.93888889, 0.90555556, 0.85555556, 0.92222222,
       0.94444444, 0.93333333, 0.97206704, 0.88268156, 0.89944134])

In [31]:
np.average(Rscores)

np.float64(0.9115332091868403)